spring.application.name=bookea-api

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.path=/api

jwt.secret=3787a4c11d382c9681b0bc0a827efd32e046bd90569a1c340f32e6273b288440
jwt.expiration=3600000
